# Critical default settings:
disable_system_gems
disable_rubygems
bundle_path ".gems/bundler_gems"

# List gems to bundle here:
gem "dm-appengine"
gem "dm-validations"
gem "sinatra"
gem "mogli", "0.0.20"
gem "json-jruby"
gem "oauth"
gem "jruby-openssl"
# testing only - appengine bundler version does not support groups yet
gem "rspec"
#gem "gherkin", "2.1.5"
#gem "rack-test"
#gem "cucumber", ">= 0.8.4"
#gem "capybara"
