gempath= ENV["GEM_PATH"].split(":")[0] #/Users/Admin/.rvm/gems/ruby-1.8.7-p302/gems"
APPENGINE_SDK_LIB_DIR= File.join(gempath, "gems", "appengine-sdk-1.4.0", "appengine-java-sdk-1.4.0", "lib")

task :default => [:test]

task :test do
  exec java_cmd + Dir.glob(File.join("**", "spec", "*_spec.rb")).join(" ")
end

task :cucumber do
  exec java_cmd + " bin/cucumber"
end

def java_cmd
  appdir = File.dirname(__FILE__)
  libdir = File.join(appdir, 'WEB-INF', 'lib')
  "java -Dfile.encoding=UTF-8 -cp #{libdir}/appengine-api-1.0-sdk-1.4.0.jar:#{libdir}/appengine-api-labs-1.4.0.jar:#{libdir}/appengine-rack.jar:#{libdir}/gems.jar:#{libdir}/generator.jar:#{libdir}/jruby-core-1.5.6.jar:#{libdir}/jruby-rack-1.0.5.jar:#{libdir}/jruby-stdlib-1.5.6.jar:#{libdir}/parser.jar:#{APPENGINE_SDK_LIB_DIR}/shared/appengine-local-runtime-shared.jar:#{APPENGINE_SDK_LIB_DIR}/impl/appengine-api-stubs.jar:#{APPENGINE_SDK_LIB_DIR}/impl/appengine-local-runtime.jar:#{APPENGINE_SDK_LIB_DIR}/testing/appengine-testing.jar org.jruby.Main "
end