
task :default => [:test]

task :test do
  appdir = File.dirname(__FILE__)
  libdir = File.join(appdir, 'WEB-INF', 'lib')
  gempath= ENV["GEM_PATH"].split(":")[0] #/Users/Admin/.rvm/gems/ruby-1.8.7-p302/gems"
  sdklibdir= File.join(gempath, "gems", "appengine-sdk-1.4.0", "appengine-java-sdk-1.4.0", "lib")
  cmd = "java -Dfile.encoding=UTF-8 -cp #{libdir}/appengine-api-1.0-sdk-1.4.0.jar:#{libdir}/appengine-api-labs-1.4.0.jar:#{libdir}/appengine-rack.jar:#{libdir}/gems.jar:#{libdir}/generator.jar:#{libdir}/jruby-core-1.5.6.jar:#{libdir}/jruby-rack-1.0.5.jar:#{libdir}/jruby-stdlib-1.5.6.jar:#{libdir}/parser.jar:#{sdklibdir}/shared/appengine-local-runtime-shared.jar:#{sdklibdir}/impl/appengine-api-stubs.jar:#{sdklibdir}/impl/appengine-local-runtime.jar:#{sdklibdir}/testing/appengine-testing.jar org.jruby.Main"
  exec cmd + " -r#{appdir}/test_environment.rb spec/models_spec.rb spec/controller_spec.rb"
end